""""""""""""""""""""""""""""""""""""
" Alex Ketchum's Vim Configuration "
""""""""""""""""""""""""""""""""""""

"Pathogen Plugin Manager
execute pathogen#infect()
filetype plugin indent on
syntax on

"Line Numbers
set number relativenumber

" Auto Toggle Relative and Absolute Line Numbers
:augroup numbertoggle
:   autocmd!
:   autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:   autocmd BufLeave,FocusLost,InsertEnter   * set number
:augroup END

" Solarized ColorScheme
syntax enable
let g:solarized_termcolors=256
set t_Co=256
set background=dark
colorscheme solarized

"Show current mode	
set showmode		
set laststatus=2

"Syntax highlighting
syntax on		

"Turn off arrowkeys
noremap <Up> <NOP> 	
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"Tabs -> spaces
set autoindent
set smartindent
set tabstop=4
set expandtab

"Searching
set ignorecase
set smartcase

